---
title: "first"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Harvest Data
Data set for Commercial Harvest from 1997 to 2019 of Iowa Lakes
First we will correct the data set by fixing the date(as date), Year(as function), Pounds(as integer) as well as, creating subsets for each lake

```{r}
harvestdata$Date <- as.Date(harvestdata$Date, "m%/d%/Y%")
harvestdata$Year <- as.factor(harvestdata$Year)
harvestdata$Pounds <- as.integer(harvestdata$Pounds)




center.sub <- subset(harvestdata, harvestdata$ï..Lake == "Center Lake" )
fiveisland.sub <- subset(harvestdata, harvestdata$ï..Lake == "Five Island Lake")
silver.sub <- subset(harvestdata, harvestdata$ï..Lake == "Silver Lake (Dickinson)")
high.sub <- subset(harvestdata, harvestdata$ï..Lake == "High Lake")
ingham.sub <- subset(harvestdata, harvestdata$ï..Lake == "Ingham Lake")
lostisland.sub <- subset(harvestdata, harvestdata$ï..Lake == "Lost Island Lake")

```

Here are summaries for each lake

```{r}
###Summaries
summary(center.sub)
summary(fiveisland.sub)
summary(high.sub)
summary(silver.sub)
summary(high.sub)
summary(ingham.sub)
summary(lostisland.sub)

```

plotting data for center lake
```{r Center Lake Plots}
plot(center.sub$Date, center.sub$Pounds)
```